language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
    - public/components
before_install:
  - npm install -g bower
install: 
  - yarn
  - bower install
script:
  - yarn run test
  - yarn run posttest
notifications:
    slack: araytek:B8Xevy6shC51ftn3tBiZR8fw